.TH ELM-REPL "1" "June 2014" "elm-repl 0.2.2.1" "User Commands"
.SH NAME
elm-repl \- Read-eval-print-loop for Elm
.SH DESCRIPTION
Elm REPL 0.2.2.1, (c) Evan Czaplicki 2011\-2013
.PP
flags [OPTIONS]
.IP
Read\-eval\-print\-loop (REPL) for digging deep into Elm projects.
.SS "Common flags:"
.TP
\fB\-c\fR \fB\-\-compiler\fR=\fIFILE\fR
Provide a path to a specific Elm compiler.
.TP
\fB\-h\fR \fB\-\-help\fR
Display help message
.TP
\fB\-v\fR \fB\-\-version\fR
Print version information
